apiVersion: apis.apps.tanzu.vmware.com/v1alpha1
kind: APIDescriptor
metadata:
  name: gateway
  annotations:
    autoscaling.knative.dev/min-scale: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{"autoscaling.knative.dev/min-scale":"1"},"labels":{"apis.apps.tanzu.vmware.com/register-api":"true","app.kubernetes.io/part-of":"gateway","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"web"},"name":"gateway","namespace":"dev-space"},"spec":{"build":{"env":[{"name":"BP_JVM_VERSION","value":"17"}]},"params":[{"name":"api_descriptor","value":{"description":"A set of API endpoints to manage the resources within the Spring Cloud Architecture app.","location":{"path":"/v3/api-docs"},"owner":"team-vmware-tanzu-se","system":"sc-architecture-system","type":"openapi"}},{"name":"testing_pipeline_params","value":{"source-sub-path":"gateway"}}],"serviceClaims":[{"name":"config-server","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ResourceClaim","name":"configserver-binding-compatible"}},{"name":"observability","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ResourceClaim","name":"observability-binding-compatible"}},{"name":"auth-client","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ResourceClaim","name":"auth-client"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/tsalm-pivotal/spring-cloud-demo-tap.git"},"subPath":"gateway"}}}
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: gateway
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: gateway
spec:
  type: openapi
  description: A set of API endpoints to manage the resources within the Spring Cloud Architecture app.
  system: sc-architecture-system
  owner: team-vmware-tanzu-se
  location:
    path: /v3/api-docs
    baseURL:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: gateway

