apiVersion: kapp.k14s.io/v1alpha1
kind: Config
waitRules:
- conditionMatchers:
  - type: ServiceAvailable
    status: "False"
    failure: true
  - type: ServiceAvailable
    status: "True"
    success: true
  resourceMatchers:
  - apiVersionKindMatcher:
      apiVersion: servicebinding.io/v1alpha3
      kind: ServiceBinding
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: payment-service-db
  annotations:
    kapp.k14s.io/identity: v1;prod-w06-s003/carto.run/Workload/payment-service;carto.run/v1alpha1
    kapp.k14s.io/original: '{"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"labels":{"app.kubernetes.io/part-of":"payment-service","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"web","kapp.k14s.io/app":"1682682534153042731","kapp.k14s.io/association":"v1.66811af644ddebaf2fdc1453c74f745f"},"name":"payment-service","namespace":"prod-w06-s003"},"spec":{"build":{"env":[{"name":"BP_JVM_VERSION","value":"17"}]},"serviceClaims":[{"name":"db","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ClassClaim","name":"postgres-1"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/tsalm-vmware/tap-workshops-payment-service.git"}}}}'
    kapp.k14s.io/original-diff-md5: c6e94dc94aed3401b5d0f26ed6c0bff3
    kapp.k14s.io/change-group: servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: payment-service
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1682682534153042731"
    kapp.k14s.io/association: v1.66811af644ddebaf2fdc1453c74f745f
    app.kubernetes.io/component: run
    carto.run/workload-name: payment-service
spec:
  name: db
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ClassClaim
    name: postgres-1
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: payment-service

