apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: payment-service-config-server
  annotations:
    autoscaling.knative.dev/min-scale: "1"
  labels:
    app.kubernetes.io/part-of: payment-service
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: payment-service
spec:
  name: config-server
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: configserver-binding-compatible
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: payment-service
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: payment-service-auth-client
  annotations:
    autoscaling.knative.dev/min-scale: "1"
  labels:
    app.kubernetes.io/part-of: payment-service
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: payment-service
spec:
  name: auth-client
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: auth-client
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: payment-service
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: payment-service-observability
  annotations:
    autoscaling.knative.dev/min-scale: "1"
  labels:
    app.kubernetes.io/part-of: payment-service
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: payment-service
spec:
  name: observability
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: observability-binding-compatible
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: payment-service

