apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: csharp-weather-forecast-v2
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: weatherforecast-steeltoe
    apps.tanzu.vmware.com/workload-type: web
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: weatherforecast-steeltoe
    app.kubernetes.io/component: run
    carto.run/workload-name: csharp-weather-forecast-v2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
          appliveview-sample/app-live-view-appflavour-check
          appliveview-sample/app-live-view-connector-steeltoe
          appliveview-sample/app-live-view-appflavours-steeltoe
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: weatherforecast-steeltoe
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: csharp-weather-forecast-v2
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.flavours: steeltoe
        tanzu.app.live.view.application.name: weatherforecast-steeltoe
    spec:
      containers:
      - image: harbor.emea.end2end.link/tap/workloads/csharp-weather-forecast-v2-dev-space@sha256:26892f335d598828551da5dec8971fbe9086f8eaa837d745ea54222649dcd30e
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

