apiVersion: kapp.k14s.io/v1alpha1
kind: Config
waitRules:
- conditionMatchers:
  - type: ServiceAvailable
    status: "False"
    failure: true
  - type: ServiceAvailable
    status: "True"
    success: true
  resourceMatchers:
  - apiVersionKindMatcher:
      apiVersion: servicebinding.io/v1alpha3
      kind: ServiceBinding
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: payment-service-config-server
  annotations:
    kapp.k14s.io/identity: v1;tap-operator-workshops-w37-s001/carto.run/Workload/payment-service;carto.run/v1alpha1
    kapp.k14s.io/original: '{"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"labels":{"app.kubernetes.io/part-of":"payment-service","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"web","kapp.k14s.io/app":"1682547714711214109","kapp.k14s.io/association":"v1.2738fa15921cb588802bf2f4a17bf23e"},"name":"payment-service","namespace":"tap-operator-workshops-w37-s001"},"spec":{"build":{"env":[{"name":"BP_JVM_VERSION","value":"17"}]},"serviceClaims":[{"name":"config-server","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ResourceClaim","name":"configserver-binding-compatible"}},{"name":"observability","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ResourceClaim","name":"observability-binding-compatible"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/tsalm-vmware/tap-workshops-payment-service.git"}}}}'
    kapp.k14s.io/original-diff-md5: c6e94dc94aed3401b5d0f26ed6c0bff3
    kapp.k14s.io/change-group: servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: payment-service
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1682547714711214109"
    kapp.k14s.io/association: v1.2738fa15921cb588802bf2f4a17bf23e
    app.kubernetes.io/component: run
    carto.run/workload-name: payment-service
spec:
  name: config-server
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: configserver-binding-compatible
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: payment-service
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: payment-service-observability
  annotations:
    kapp.k14s.io/identity: v1;tap-operator-workshops-w37-s001/carto.run/Workload/payment-service;carto.run/v1alpha1
    kapp.k14s.io/original: '{"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"labels":{"app.kubernetes.io/part-of":"payment-service","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"web","kapp.k14s.io/app":"1682547714711214109","kapp.k14s.io/association":"v1.2738fa15921cb588802bf2f4a17bf23e"},"name":"payment-service","namespace":"tap-operator-workshops-w37-s001"},"spec":{"build":{"env":[{"name":"BP_JVM_VERSION","value":"17"}]},"serviceClaims":[{"name":"config-server","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ResourceClaim","name":"configserver-binding-compatible"}},{"name":"observability","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ResourceClaim","name":"observability-binding-compatible"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/tsalm-vmware/tap-workshops-payment-service.git"}}}}'
    kapp.k14s.io/original-diff-md5: c6e94dc94aed3401b5d0f26ed6c0bff3
    kapp.k14s.io/change-group: servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: payment-service
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1682547714711214109"
    kapp.k14s.io/association: v1.2738fa15921cb588802bf2f4a17bf23e
    app.kubernetes.io/component: run
    carto.run/workload-name: payment-service
spec:
  name: observability
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: observability-binding-compatible
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: payment-service

