apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: config-server
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    apps.tanzu.vmware.com/workload-type: web
    learningcenter.tanzu.vmware.com/component: session
    learningcenter.tanzu.vmware.com/environment.name: developer-workshops-w01
    learningcenter.tanzu.vmware.com/portal.name: developer-workshops
    learningcenter.tanzu.vmware.com/session.name: developer-workshops-w01-s007
    learningcenter.tanzu.vmware.com/session.objects: "true"
    learningcenter.tanzu.vmware.com/workshop.name: modern-app-arch-spring-cloud-workshop
    app.kubernetes.io/component: run
    carto.run/workload-name: config-server
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        boot.spring.io/actuator: http://:8081/actuator
        boot.spring.io/version: 3.1.2
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/spring-boot
          spring-boot-convention/spring-boot-graceful-shutdown
          spring-boot-convention/spring-boot-web
          spring-boot-convention/spring-boot-actuator
          spring-boot-convention/spring-boot-actuator-probes
          spring-boot-convention/app-live-view-appflavour-check
          spring-boot-convention/app-live-view-connector-boot
          spring-boot-convention/app-live-view-appflavours-boot
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        apps.tanzu.vmware.com/auto-configure-actuators: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: config-server
        conventions.carto.run/framework: spring-boot
        learningcenter.tanzu.vmware.com/component: session
        learningcenter.tanzu.vmware.com/environment.name: developer-workshops-w01
        learningcenter.tanzu.vmware.com/portal.name: developer-workshops
        learningcenter.tanzu.vmware.com/session.name: developer-workshops-w01-s007
        learningcenter.tanzu.vmware.com/session.objects: "true"
        learningcenter.tanzu.vmware.com/workshop.name: modern-app-arch-spring-cloud-workshop
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.actuator.path: actuator
        tanzu.app.live.view.application.actuator.port: "8081"
        tanzu.app.live.view.application.flavours: spring-boot
        tanzu.app.live.view.application.name: config-server
    spec:
      containers:
      - env:
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
          value: https://gitea.emea.end2end.link/gitea_admin/externalized-configuration.git
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL
          value: developer-workshops-w01-s007
        - name: JAVA_TOOL_OPTIONS
          value: -Dmanagement.endpoint.health.probes.add-additional-paths="true" -Dmanagement.endpoint.health.show-details="always" -Dmanagement.endpoints.web.base-path="/actuator" -Dmanagement.endpoints.web.exposure.include="*" -Dmanagement.health.probes.enabled="true" -Dmanagement.server.port="8081" -Dserver.port="8080" -Dserver.shutdown.grace-period="24s"
        image: harbor.emea.end2end.link/tap/workloads/config-server-developer-workshops-w01-s007@sha256:0c26f124965388e3e21f70b5486eddab3524c9e6c6fd63f78f3fa0cfc01a14fd
        livenessProbe:
          httpGet:
            path: /livez
            port: 8080
            scheme: HTTP
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

